
### Register player:

POST {{url}}/register
Content-Type: application/json

{
    "playerName": "testbot2"
}

> {% client.global.set("playerId", response.body.id); %}


### Get the current gamestate

GET {{url}}/gamestate


### Register your next move
# One of UP, DOWN, LEFT, RIGHT, PICK, USE

PUT {{url}}/{{playerId}}/move
Content-Type: application/json

"LEFT"


### Say hello to others

POST {{url}}/{{playerId}}/say
Content-Type: application/json

"hello!"

